name = "CognitiveWorkload"
uuid = "77a2d163-1e95-47b8-a916-e2f2ba09f7e1"
authors = ["itsdfish"]
version = "0.0.1"

[deps]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
SafeTestsets = "0.0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
